#!/bin/bash

export ARCH="arm64"
export KBUILD_BUILD_USER="wulan17"
export KBUILD_BUILD_HOST="Github"
export KERNEL_NAME="Mayuri"

## Notes:
# this script running in aarch64 workflows
# so only use clang for aarch64
export CLANG_URL="https://github.com/wulan17/tc-build/releases/download/21.0.0git-dca74f794/Mayuri-clang_21.0.0gitgit-bookworm-aarch64-dca74f794.tar.xz"

export CORES=$(nproc --all)

# START OF DO NOT EDIT
export BASE_DIR="$(pwd)"
export ZIP_DIR="$BASE_DIR"/AnyKernel
export CLANG_NAME="$(basename "$CLANG_URL")"
export PATH="$BASE_DIR/clang/bin:/usr/lib/ccache:$PATH"

# autogenerated by do_write_config
# Reserved
# END OF DO NOT EDIT

if [[ -n "$B_TYPE" ]]; then
    if [[ "$B_TYPE" == "susfs" ]]; then
        export ZIP_NAME="$GITHUB_RUN_ID-$KERNEL_NAME-kernel-$DEVICE-rksu-susfs-"$(env TZ='Asia/Jakarta' date +%Y%m%d)
    elif [[ "$B_TYPE" == "ksu" ]]; then
        export ZIP_NAME="$GITHUB_RUN_ID-$KERNEL_NAME-kernel-$DEVICE-rksu-"$(env TZ='Asia/Jakarta' date +%Y%m%d)
    else
        export ZIP_NAME="$GITHUB_RUN_ID-$KERNEL_NAME-kernel-$DEVICE-"$(env TZ='Asia/Jakarta' date +%Y%m%d)
    fi
fi
