name: Build Kernel on AArch64

on:
  workflow_dispatch:
    inputs:
      kernel_repo:
        description: 'Kernel repository to build'
        required: true
        default: 'Mayuri-Chan/android_kernel_xiaomi_gale'
      kernel_branch:
        description: 'Kernel branch to build'
        required: true
        default: 'stable'
      kernelsu_repo:
        description: 'Kernelsu repository to build'
        required: true
        default: 'rsuntk/KernelSU'
      kernel_defconfig:
        description: 'defconfig to build the kernel'
        required: true
        default: 'gale_defconfig'
      kernelsu_branch:
        description: 'Kernelsu branch to build'
        required: true
        default: 'main'
      kernelsu_susfs_repo:
        description: 'SUSFS repository to build'
        required: true
        default: 'rsuntk/KernelSU'
      kernelsu_susfs_branch:
        description: 'SUSFS branch to build'
        required: true
        default: 'susfs-rksu-master'
      kernel_img:
        description: 'Kernel image name'
        required: false
        default: 'Image.gz'
      kernel_dtb:
        description: 'Kernel dtb name'
        required: false
        default: 'mediatek/mt6768.dtb'


jobs:
  build_kernel:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        build_type: ["normal", "ksu", "susfs"]
    container:
      image: wulan17/debian-aarch64:latest
    steps:
      - name: Checkout script
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt upgrade -y
          apt install -y ccache wget bc build-essential make autoconf automake git bison pahole flex libssl-dev zip jq cpio aria2 gh python3 python-is-python3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Clone kernel
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.kernel_repo }}
          path: kernel
          ref: ${{ github.event.inputs.kernel_branch }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: "false"

      - name: Clone kernelsu
        if: ${{ matrix.build_type == 'ksu' || matrix.build_type == 'susfs' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.build_type == 'ksu' && github.event.inputs.kernelsu_repo || github.event.inputs.kernelsu_susfs_repo }}
          path: kernel/KernelSU
          ref: ${{ matrix.build_type == 'ksu' && github.event.inputs.kernelsu_branch || github.event.inputs.kernelsu_susfs_branch }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: "false"

      - name: Write Config
        run: bash build.sh write_config
        env:
          KERNEL_DEFCONFIG: ${{ github.event.inputs.kernel_defconfig }}
          BUILD_TYPE: ${{ matrix.build_type }}
          KERNEL_IMG: ${{ github.event.inputs.kernel_img }}
          KERNEL_DTB: ${{ github.event.inputs.kernel_dtb }}

      - name: Setup Clang
        run: bash build.sh clang

      - name: Build Kernel
        run: bash build.sh kernel

      - name: Compress AnyKernel
        run: bash build.sh anykernel

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build_type }}-build-logs
          path: Logs/

      - name: Release kernel
        run: bash build.sh release
